import matplotlib.pyplot as plt
import pandas as pd

# Read the CSV file generated by C++
df = pd.read_csv("quicksort_runtime.csv")

# Extracting values
n_values = df["n"]
runtime_ns = df["runtime_ns"]
n_log_n = df["n_log_n"]
n_squared = df["n_squared"]

# Plot actual QuickSort runtime
plt.plot(df["n"], df["runtime_ns"], linestyle="solid", color="blue", label="QuickSort Runtime")

# Plot O(n log n) and O(n²) complexity
plt.plot(n_values, n_log_n, linestyle='solid', label="O(n log n)", color='green')
plt.plot(n_values, n_squared, linestyle='solid', label="O(n²)", color='red')

# Labels and Title
plt.xlabel("Input Size (n)")
plt.ylabel("Time (nanoseconds)")
plt.title("QuickSort Runtime vs. Complexity Analysis")
plt.yscale("log")  # Log scale for better visualization


plt.legend()
plt.grid(True)
plt.show()
